const { app } = require('electron');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const CONFIG_PATH = path.join(app.getPath('userData'), 'config.json');

/**
 * Persistent local state. Only these four fields live on disk:
 *
 *   installationId  — uuid v4 generated by the kiosk on first launch.
 *                     Written once by `saveInstallation` and never
 *                     mutated. Identifies this machine to the backend.
 *   locationId      — uuid entered by the operator on the setup screen.
 *   spaceId         — uuid chosen from the picker on the setup screen.
 *   adminPassword   — local admin panel password (defaults to admin123).
 *
 * Everything else that used to live in config.json (apiBaseUrl,
 * shellyIP, projectorSettings, extensionSettings, leagueSettings) is
 * server-managed via `/kiosk/settings/:installationId` and updated in
 * real time over the socket.
 */

function readRaw() {
  if (!fs.existsSync(CONFIG_PATH)) return null;
  try {
    const data = fs.readFileSync(CONFIG_PATH, 'utf8');
    return JSON.parse(data);
  } catch (err) {
    console.error('Failed to parse config.json:', err.message);
    return null;
  }
}

function writeRaw(obj) {
  const backupPath = CONFIG_PATH + '.backup';
  if (fs.existsSync(CONFIG_PATH)) {
    try {
      fs.copyFileSync(CONFIG_PATH, backupPath);
    } catch (err) {
      console.warn('Failed to back up config.json:', err.message);
    }
  }
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(obj, null, 4));
}

/**
 * Load the installation identity. Returns null if any required field
 * is missing — the caller launches the setup wizard in that case.
 */
function loadInstallation() {
  const raw = readRaw();
  if (!raw) return null;
  if (!raw.installationId || !raw.locationId || !raw.spaceId) return null;
  return {
    installationId: raw.installationId,
    locationId: raw.locationId,
    spaceId: raw.spaceId,
    adminPassword: raw.adminPassword || 'admin123',
  };
}

/**
 * Save the installation identity after the setup wizard completes.
 * Preserves the adminPassword if it already exists on disk (e.g.
 * re-registering after a clear-installation bump from the dashboard).
 *
 * This function intentionally builds the output object field-by-field
 * instead of spreading `existing` — that way any zombie keys left over
 * from the old config.json format (apiBaseUrl, shellyIP,
 * projectorSettings, etc.) are dropped, not silently preserved. The
 * four fields below are the entire on-disk schema.
 */
function saveInstallation({ installationId, locationId, spaceId, adminPassword }) {
  const existing = readRaw() ?? {};
  const next = {
    installationId,
    locationId,
    spaceId,
    adminPassword: adminPassword ?? (existing.adminPassword || 'admin123'),
  };
  writeRaw(next);
  return next;
}

/**
 * Update just the admin password (used by admin panel change-password
 * flow). Leaves identity fields untouched.
 */
function updateAdminPassword(newHash) {
  const existing = loadInstallation();
  if (!existing) throw new Error('Cannot update password: no installation loaded');
  return saveInstallation({ ...existing, adminPassword: newHash });
}

function generateInstallationId() {
  return crypto.randomUUID();
}

/**
 * Delete the installation file so the next launch drops into the
 * setup wizard. Used by the "Clear assigned kiosk" flow triggered
 * from the dashboard — the kiosk receives a restart command, quits,
 * and on relaunch has no installation to resume.
 *
 * We keep the adminPassword so the operator doesn't have to reset it.
 */
function clearInstallation() {
  const existing = readRaw();
  if (!existing) return;
  const preserved = { adminPassword: existing.adminPassword || 'admin123' };
  writeRaw(preserved);
}

module.exports = {
  CONFIG_PATH,
  loadInstallation,
  saveInstallation,
  updateAdminPassword,
  generateInstallationId,
  clearInstallation,
};
